# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-14 12:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import socialaccess.models


class Migration(migrations.Migration):

    dependencies = [
        ('socialaccess', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GithubProfile',
            fields=[
                ('oauthprofile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='socialaccess.OAuthProfile')),
                ('uid', models.CharField(max_length=128)),
            ],
            bases=('socialaccess.oauthprofile', socialaccess.models.ProfileModelMixin),
        ),
    ]
