# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-21 16:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socialaccess', '0002_githubprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oauthprofile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oauth_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
